version: '3.1'

services:

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    networks:
      - spiderdatabase
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    command: "--bind_ip_all"
    # command: "--bind_ip_all --replSet rs"
    # if you use those compose first time, rs.initiate() with admin auth first
    # if you are using change stream, you should use replica set


  mongo-express:
    container_name: mongoexpress
    image: mongo-express
    restart: always
    networks:
      - spiderdatabase
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin  
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo

networks:
  spiderdatabase: